<?php

declare(strict_types=1);

namespace PhpFastForward\Brand;

use RuntimeException;

/** Render the approved fox geometry and outlined Exo 2 lettering. */
final class BrandLogos
{
    private static function xml(string $text): string
    {
        return htmlspecialchars($text, ENT_XML1 | ENT_QUOTES, 'UTF-8');
    }

    private static function lettering(array $source, string $text, int $x, int $baseline, int $size, array $colors): array
    {
        $font = $source['lettering'];
        $scale = $size / $font['units_per_em'];
        $cursor = (float) $x;
        $paths = [];
        foreach (str_split($text) as $index => $character) {
            $glyph = $font['glyphs'][$character];
            $role = $text === 'FastForward' && $index < 4 ? 'orange' : 'lettering';
            $paths[] = sprintf('<path fill="%s" transform="translate(%.4f %d) scale(%.6f %.6f)" d="%s"/>', $colors[$role], $cursor, $baseline, $scale, -$scale, self::xml($glyph['path']));
            $cursor += $glyph['advance'] * $scale;
            $cursor += ($font['kerning'][substr($text, $index, 2)] ?? 0) * $scale;
            if ($text === 'FastForward' && $index === 3) {
                $cursor += $source['layout']['word_gap'];
            }
        }

        return [implode("\n", $paths), $cursor];
    }

    public static function render(array $source, string $variant, bool $markOnly): string
    {
        $colors = $source['variants'][$variant];
        foreach ($colors as $color) {
            if (!is_string($color) || !preg_match('/^#[0-9a-f]{3}(?:[0-9a-f]{3})?$/iD', $color)) {
                throw new RuntimeException('Logo paints must be opaque hexadecimal colors');
            }
        }
        $mono = in_array($variant, ['ink', 'white'], true);
        $parts = $source['symbol']['paths'];
        $positive = array_filter($parts, fn ($part) => !in_array($part['role'], ['cream', 'eye', 'nose'], true));
        $cutouts = array_filter($parts, fn ($part) => $part['role'] === 'cream');
        $body = [];
        if ($mono) {
            $body[] = '<defs><mask id="fox-knockout" maskUnits="userSpaceOnUse" x="0" y="0" width="320" height="320">';
            $body[] = '<rect width="320" height="320" fill="#fff"/>';
            foreach ($cutouts as $part) {
                $body[] = '<path fill="#000" stroke="#000" stroke-width="2" d="' . self::xml($part['d']) . '"/>';
            }
            $body[] = '</mask></defs><g mask="url(#fox-knockout)">';
        }
        foreach ($positive as $part) {
            $body[] = '<path fill="' . $colors[$part['role']] . '" d="' . self::xml($part['d']) . '"/>';
        }
        if ($mono) {
            $body[] = '</g>';
        } else {
            foreach ($cutouts as $part) {
                $body[] = '<path fill="' . $colors[$part['role']] . '" d="' . self::xml($part['d']) . '"/>';
            }
        }
        foreach ($parts as $part) {
            if (in_array($part['role'], ['eye', 'nose'], true)) {
                $body[] = '<path fill="' . $colors[$part['role']] . '" d="' . self::xml($part['d']) . '"/>';
            }
        }
        $width = 320;
        if (!$markOnly) {
            $layout = $source['layout'];
            foreach ($layout['lines'] as $line) {
                [$paths, $right] = self::lettering($source, $line['text'], $layout['x'], $line['baseline'], $line['size'], $colors);
                $body[] = $paths;
                $width = max($width, (int) ceil($right + $layout['right_padding']));
            }
        }
        $label = $markOnly ? 'Dash fox mark' : 'PHP Fast Forward';

        return '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 ' . $width . ' 320" role="img" aria-labelledby="title">' . "\n"
            . '<title id="title">' . $label . '</title>' . "\n"
            . '<!-- Generated by scripts/build-brand-logos.php; edit assets/brand/logo-source.json. -->' . "\n"
            . implode("\n", $body) . "\n</svg>\n";
    }

    /** @return array<string,string> */
    public static function outputs(string $root): array
    {
        $source = json_decode(file_get_contents($root . '/assets/brand/logo-source.json'), true, flags: JSON_THROW_ON_ERROR);
        foreach ($source['lettering']['source_files'] as $item) {
            if (!is_file($root . '/' . $item['path']) || hash_file('sha256', $root . '/' . $item['path']) !== $item['sha256']) {
                throw new RuntimeException('Font source changed: ' . $item['path']);
            }
        }
        $outputs = [];
        foreach ([false, true] as $markOnly) {
            $stem = $markOnly ? 'fast-forward-mark' : 'fast-forward-logo';
            foreach (['color', 'dark', 'ink', 'white'] as $variant) {
                $suffix = $variant === 'color' ? '' : '-' . $variant;
                $outputs['assets/brand/' . $stem . $suffix . '.svg'] = self::render($source, $variant, $markOnly);
            }
        }

        return $outputs;
    }

    public static function build(string $root, bool $check): int
    {
        $outputs = self::outputs($root);
        foreach ($outputs as $relative => $content) {
            $path = $root . '/' . $relative;
            if ($check) {
                if (!is_file($path) || file_get_contents($path) !== $content) {
                    throw new RuntimeException('Stale logo export: ' . $relative);
                }
            } elseif (file_put_contents($path, $content) === false) {
                throw new RuntimeException('Cannot write logo export: ' . $relative);
            }
        }

        return count($outputs);
    }
}
