#!/usr/bin/env python3
"""Build the Dash fox signature from reviewed geometry and outlined lettering."""

import argparse
import hashlib
import json
from pathlib import Path
from xml.sax.saxutils import escape

ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / "assets/brand/logo-source.json"


def sha256(path):
    return hashlib.sha256(path.read_bytes()).hexdigest()


def lettering(source, text, x, baseline, size, colors):
    font = source["lettering"]
    scale = size / font["units_per_em"]
    cursor = x
    paths = []
    for index, char in enumerate(text):
        glyph = font["glyphs"][char]
        role = "orange" if text == "FastForward" and index < 4 else "lettering"
        paths.append(
            f'<path fill="{colors[role]}" transform="translate({cursor:.4f} {baseline}) '
            f'scale({scale:.6f} {-scale:.6f})" d="{escape(glyph["path"])}"/>'
        )
        cursor += glyph["advance"] * scale
        pair = text[index:index + 2]
        cursor += font.get("kerning", {}).get(pair, 0) * scale
        if text == "FastForward" and index == 3:
            cursor += source["layout"]["word_gap"]
    return "\n".join(paths), cursor


def render(source, variant, mark_only):
    colors = source["variants"][variant]
    mono = variant in ("ink", "white")
    parts = source["symbol"]["paths"]
    positive = [part for part in parts if part["role"] not in ("cream", "eye", "nose")]
    cutouts = [part for part in parts if part["role"] == "cream"]
    body = []
    if mono:
        body.append('<defs><mask id="fox-knockout" maskUnits="userSpaceOnUse" x="0" y="0" width="320" height="320">')
        body.append('<rect width="320" height="320" fill="#fff"/>')
        body += [f'<path fill="#000" stroke="#000" stroke-width="2" d="{escape(p["d"])}"/>' for p in cutouts]
        body.append('</mask></defs><g mask="url(#fox-knockout)">')
    body += [f'<path fill="{colors[p["role"]]}" d="{escape(p["d"])}"/>' for p in positive]
    if mono:
        body.append('</g>')
    else:
        body += [f'<path fill="{colors[p["role"]]}" d="{escape(p["d"])}"/>' for p in cutouts]
    body += [f'<path fill="{colors[p["role"]]}" d="{escape(p["d"])}"/>' for p in parts if p["role"] in ("eye", "nose")]
    width = 320
    if not mark_only:
        layout = source["layout"]
        for line in layout["lines"]:
            paths, right = lettering(source, line["text"], layout["x"], line["baseline"], line["size"], colors)
            body.append(paths)
            width = max(width, int(right + layout["right_padding"] + 0.999))
    label = "Dash fox mark" if mark_only else "PHP Fast Forward"
    return (
        f'<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 {width} 320" role="img" aria-labelledby="title">\n'
        f'<title id="title">{label}</title>\n'
        '<!-- Generated by scripts/build-brand-logos.py; edit assets/brand/logo-source.json. -->\n'
        + "\n".join(body) + '\n</svg>\n'
    )


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    source = json.loads(SOURCE.read_text(encoding="utf-8"))
    for item in source["lettering"]["source_files"]:
        if sha256(ROOT / item["path"]) != item["sha256"]:
            raise SystemExit(f'Font source changed: {item["path"]}')
    outputs = []
    for mark_only in (False, True):
        stem = "fast-forward-mark" if mark_only else "fast-forward-logo"
        for variant in ("color", "dark", "ink", "white"):
            suffix = "" if variant == "color" else f"-{variant}"
            target = ROOT / f"assets/brand/{stem}{suffix}.svg"
            # UTF-8 bytes retain the renderer's LF separators on every platform.
            content = render(source, variant, mark_only).encode("utf-8")
            if args.check:
                if not target.is_file() or target.read_bytes() != content:
                    raise SystemExit(f"Stale logo export: {target.relative_to(ROOT)}")
            else:
                target.write_bytes(content)
            outputs.append(str(target.relative_to(ROOT)))
    print(f'{"Verified" if args.check else "Built"} {len(outputs)} SVG logo exports.')


if __name__ == "__main__":
    main()
